import { mkdirSync, readdirSync, rmSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { build } from "esbuild";

const root = process.cwd();
const fileDir = join(root, "file-dist");

rmSync(fileDir, { recursive: true, force: true });
mkdirSync(fileDir, { recursive: true });

await build({
  entryPoints: [join(root, "src", "main.ts")],
  bundle: true,
  format: "iife",
  target: "es2022",
  outdir: fileDir,
  entryNames: "game",
  assetNames: "assets/[name]",
  logLevel: "silent"
});

const files = readdirSync(fileDir);
const script = files.find((file) => file.endsWith(".js"));
const css = files.find((file) => file.endsWith(".css"));
if (!script || !css) {
  throw new Error("Direct-file build did not produce game JS and CSS");
}

const html = `<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Blockstead Direct</title>
    <link rel="stylesheet" href="./file-dist/${css}" />
    <script defer src="./file-dist/${script}"></script>
  </head>
  <body>
    <div id="app"></div>
  </body>
</html>
`;

writeFileSync(join(root, "index.html"), html);
writeFileSync(
  join(fileDir, "README.txt"),
  "This directory is generated by npm run build:file. Open ../index.html directly in a browser.\n"
);
